# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gmail-britta 0.1.7 ruby lib

Gem::Specification.new do |s|
  s.name = "gmail-britta"
  s.version = "0.1.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Andreas Fuchs"]
  s.date = "2016-01-29"
  s.description = "This gem helps create large (>50) gmail filter chains by writing xml compatible with gmail's \"import/export filters\" feature."
  s.email = "asf@boinkor.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    ".yardopts",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "THANKS.md",
    "TODO.org",
    "VERSION",
    "examples/Gemfile",
    "examples/Gemfile.lock",
    "examples/README.md",
    "examples/asf.rb",
    "gmail-britta.gemspec",
    "lib/gmail-britta.rb",
    "lib/gmail-britta/chaining_filter.rb",
    "lib/gmail-britta/filter.rb",
    "lib/gmail-britta/filter_set.rb",
    "lib/gmail-britta/single_write_accessors.rb",
    "test/test_gmail-britta.rb"
  ]
  s.homepage = "http://github.com/antifuchs/gmail-britta"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.5"
  s.summary = "Create complex gmail filtersets with a ruby DSL."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, ["~> 3.1.6"])
      s.add_development_dependency(%q<rake>, [">= 0.9.2"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.2.0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<haml>, ["~> 3.1.6"])
      s.add_dependency(%q<rake>, [">= 0.9.2"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.2.0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<haml>, ["~> 3.1.6"])
    s.add_dependency(%q<rake>, [">= 0.9.2"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.2.0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

